name: Deploy Flask App to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          # Usa el secreto SSH_PRIVATE_KEY para configurar la clave privada
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          # Agrega el host EC2 al archivo known_hosts usando el secreto EC2_HOST
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          set -e  # Detener el script si ocurre un error
          ssh ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
          cd /home/ubuntu/app
          git pull origin main
          source venv/bin/activate
          pip install -r requirements.txt
          sudo systemctl restart gunicorn
          EOF
